package shared

import (
	"math/rand"
	"time"
)

// ========== COMPILER INSTRUCTION STRUCTURES ==========

// AutomationInstruction is a complete instruction set generated by the compiler
// and sent to listeners for execution
type AutomationInstruction struct {
	Platform       string                 `json:"platform"`
	SubtypeID      string                 `json:"subtype_id,omitempty"`
	AccountID      string                 `json:"account_id"`
	TicketID       string                 `json:"ticket_id"`
	Action         string                 `json:"action"`
	Intent         string                 `json:"intent"`
	Steps          []InstructionStep      `json:"steps"`
	MaxRetries     int                    `json:"max_retries"`
	Timeout        time.Duration          `json:"timeout_ms"`
	Priority       int                    `json:"priority"`
	FallbackSteps  []InstructionStep      `json:"fallback_steps,omitempty"`
	NotificationID string                 `json:"notification_id"`
	OriginalText   string                 `json:"original_text"`
	Data           map[string]interface{} `json:"data"`
	CreatedAt      time.Time              `json:"created_at"`
}

// InstructionStep is a single step in an automation instruction
type InstructionStep struct {
	Type        string                 `json:"type"`
	Selector    string                 `json:"selector,omitempty"`
	Value       string                 `json:"value,omitempty"`
	DelayBefore int                    `json:"delay_before_ms"`
	DelayAfter  int                    `json:"delay_after_ms"`
	Description string                 `json:"description"`
	RetryCount  int                    `json:"retry_count"`
	Condition   string                 `json:"condition,omitempty"`
	Options     map[string]interface{} `json:"options,omitempty"`
}

// ========== STEP TYPE CONSTANTS ==========

const (
	StepTypeNavigate       = "navigate"
	StepTypeClick          = "click"
	StepTypeType           = "type"
	StepTypeWait           = "wait"
	StepTypeScroll         = "scroll"
	StepTypeJavaScript     = "js"
	StepTypePress          = "press"
	StepTypeAPICall        = "api_call"
	StepTypeSendMessage    = "send_message"
	StepTypeReply          = "reply"
	StepTypeLike           = "like"
	StepTypeFollow         = "follow"
	StepTypeUnfollow       = "unfollow"
	StepTypeBlock          = "block"
	StepTypeRateLimitCheck = "rate_limit_check"
	StepTypeDBUpdate       = "db_update"
	StepTypeDBRecord       = "db_record"
	StepTypeAIGenerate     = "ai_generate"
	StepTypeLog            = "log"
	StepTypeSave           = "save"
	StepTypeShare          = "share"
	StepTypeSearch         = "search"
	StepTypeUpload         = "upload"
	StepTypeDownload       = "download"
	StepTypeReact          = "react"
	StepTypePost           = "post"
)

// ========== ACTION TYPE CONSTANTS ==========

const (
	ActionBlock                = "block"
	ActionUnfollow             = "unfollow"
	ActionNoop                 = "noop"
	ActionQueued               = "queued"
	ActionAutoHeart            = "auto_heart"
	ActionSendGreeting         = "send_greeting"
	ActionSendStoreInfo        = "send_store_info"
	ActionSendProduct          = "send_product"
	ActionSendOrderTemplate    = "send_order_template"
	ActionSendStockWarning     = "send_stock_warning"
	ActionSendCancellation     = "send_cancellation"
	ActionSendFallback         = "send_fallback"
	ActionAskProduct           = "ask_product"
	ActionAskForOrder          = "ask_for_order"
	ActionAskOrderConfirmation = "ask_order_confirmation"
	ActionAIResponse           = "ai_response"
	ActionReact                = "react"
	ActionShare                = "share"
	ActionSave                 = "save"
	ActionSearch               = "search"
	ActionUpload               = "upload"
	ActionDownload             = "download"
	ActionFollow               = "follow"
)

// ========== INTENT TYPE CONSTANTS ==========

const (
	IntentGreeting          = "greeting"
	IntentProductInquiry    = "product_inquiry"
	IntentPriceQuery        = "price_query"
	IntentOrderIntent       = "order_intent"
	IntentOrderConfirmation = "order_confirmation"
	IntentStockCheck        = "stock_check"
	IntentStoreInfo         = "store_info"
	IntentWholesaleInquiry  = "wholesale_inquiry"
	IntentSpam              = "spam"
	IntentAbusive           = "abusive"
	IntentComplexQuery      = "complex_query"
	IntentFeedback          = "feedback"
	IntentComplaint         = "complaint"
	IntentCancellation      = "cancellation"
	IntentReturn            = "return"
	IntentShippingQuery     = "shipping_query"
	IntentPaymentIssue      = "payment_issue"
	IntentTechnicalIssue    = "technical_issue"
)

// ========== PLATFORM CONSTANTS ==========

const (
	PlatformFacebook  = "facebook"
	PlatformInstagram = "instagram"
	PlatformTwitter   = "twitter"
	PlatformTelegram  = "telegram"
	PlatformWhatsApp  = "whatsapp"
	PlatformViber     = "viber"
)

// ========== HELPER FUNCTIONS ==========

// GenerateRandomID generates a random ID string
func GenerateRandomID(length int) string {
	const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	b := make([]byte, length)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// Min returns the minimum of two integers
func Min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ========== COMPILER RESULT CODES ==========

const (
	ResultSuccess        = "success"
	ResultFailed         = "failed"
	ResultRateLimited    = "rate_limited"
	ResultInvalidInput   = "invalid_input"
	ResultPlatformError  = "platform_error"
	ResultNetworkError   = "network_error"
	ResultAuthError      = "auth_error"
	ResultTimeout        = "timeout"
	ResultPartialSuccess = "partial_success"
	ResultSkipped        = "skipped"
	ResultQueued         = "queued"
)
